### ISSUE TITLE
config

### ISSUE THREAD

**Issue by shaurgon** [Rwandered/shd-project#1]
Спрячь )) И пароль смени
`.env` для таких вещей используется

https://github.com/Rwandered/shd-project/blob/e5761a816ee922e19f4f5ef78aedc7eb6158d9b7/config/default.json#L3

**Comment by shaurgon** [comment]
> И пароль смени

Видимо, везде xD

**Comment by Rwandered** [comment]
Да,нужно закрыть, это случайный пароль)
